name: MultiArchDockerBuild

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_multi_arch_image:
    name: Build multi-arch Docker image.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set environment variables
        run:  echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push main
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: |
            shneezin/breitbandmessung
            shneezin/breitbandmessung:${{ github.sha }}
          platforms: linux/amd64, linux/arm64/v8
          build-args: |
            COMMIT_SHA=${{ github.sha }}
            BRANCH=${{ env.GIT_BRANCH }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}

      - name: Build and push dev
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          ile: Dockerfile.debian
          tags: |
            shneezin/breitbandmessung-node:dev
          platforms: linux/amd64
          build-args: |
            COMMIT_SHA=${{ github.sha }}
            BRANCH=${{ env.GIT_BRANCH }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}
